[package]
edition = "2021"
name = "difference-of-squares"
version = "1.2.0"

[dependencies]
criterion = { version = "0.5.1", optional = true }

[features]
benchmarks = ["dep:criterion"]

[[bench]]
name = "difference_of_squares_bench"
harness = false
