[dependencies]
unicode-segmentation = { version = "1", optional = true }

[features]
default = ["grapheme"]
grapheme = ["dep:unicode-segmentation"]

[package]
edition = "2021"
name = "reverse_string"
version = "1.2.0"
